services:
  app:
    container_name: cn-visita-medica
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8188:4321'
    volumes:
      - ./public/uploads:/app/public/uploads
    environment:
      HOST: '0.0.0.0'
      PORT: '4321'
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER:-usr_visita_medica}
      DB_PASSWORD: ${DB_PASSWORD:-pwd_visita_medica}
      DB_NAME: ${DB_NAME:-db_visita_medica}      
    restart: unless-stopped
